"""
Module with settings related to the HUD sprite.
"""
HUD_WIDTH = 100

HUD_HEIGHT = 80

HUD_SPRITESHEET_POSITION = (0, 0, 319, 32)  # HUD only spritesheet now

SILVER_ALPHANUMERIC_SPRITE_POSITION = (30, 1088, 318, 15)
GOLDEN_NUMERIC_SPRITE_POSITION = (30, 1100, 318, 14)
ALPHANUMERIC_CHARACTER_WIDTH_HEIGHT = (13, 13)  # width, height

DEFAULT_SPRITESHEET_GOLDEN_NUMBER_DIMENSIONS = {"width": 9, "height": 10}
GOLDEN_NUMBERS_ON_SCREEN_DIMENSIONS = {"width": 23, "height": 23}
