"""
Module with levels and levels char code configuration.
"""
DEFAULT_SPRITESHEET_LEVELS_CHARCODE_LENGTH = 8

DEFAULT_SPRITESHEET_JAZZ_CHARCODE = "JJJJJJJJ"
DEFAULT_SPRITESHEET_NO_PLATFORM_CHARCODE = "........"

DEFAULT_SPRITESHEET_TILE_DIMENSIONS = {"width": 32, "height": 32}
