sudo: false
language: python
python:
  - "3.7-dev"
install:
  - pip install pipenv
  - pipenv install --dev --system --deploy --ignore-pipfile

before_script:
  # gets binary file for codeclimate to generate the coverage of the project (badge)
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - tox

after_script:
  # sends the coverage report to codeclimate
  - ./cc-test-reporter after-build -d -t coverage.py --exit-code $TRAVIS_TEST_RESULT